apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cart-secrets
  namespace: retail-store
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "${CLUSTER_NAME}/cart"
        objectType: "secretsmanager"
        jmesPath:
          - path: RETAIL_CART_PERSISTENCE_PROVIDER
            objectAlias: RETAIL_CART_PERSISTENCE_PROVIDER
          - path: RETAIL_CART_PERSISTENCE_DYNAMODB_TABLE_NAME
            objectAlias: RETAIL_CART_PERSISTENCE_DYNAMODB_TABLE_NAME
          - path: RETAIL_CART_PERSISTENCE_DYNAMODB_CREATE_TABLE
            objectAlias: RETAIL_CART_PERSISTENCE_DYNAMODB_CREATE_TABLE
  secretObjects:
  - secretName: cart-secrets
    type: Opaque
    data:
    - objectName: RETAIL_CART_PERSISTENCE_PROVIDER
      key: RETAIL_CART_PERSISTENCE_PROVIDER
    - objectName: RETAIL_CART_PERSISTENCE_DYNAMODB_TABLE_NAME
      key: RETAIL_CART_PERSISTENCE_DYNAMODB_TABLE_NAME
    - objectName: RETAIL_CART_PERSISTENCE_DYNAMODB_CREATE_TABLE
      key: RETAIL_CART_PERSISTENCE_DYNAMODB_CREATE_TABLE
